USE [master]
GO
/****** Object:  Database [pract15]    Script Date: 22.12.2025 21:41:07 ******/
CREATE DATABASE [pract15]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'pract15', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\pract15.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'pract15_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\pract15_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [pract15] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [pract15].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [pract15] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [pract15] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [pract15] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [pract15] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [pract15] SET ARITHABORT OFF 
GO
ALTER DATABASE [pract15] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [pract15] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [pract15] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [pract15] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [pract15] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [pract15] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [pract15] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [pract15] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [pract15] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [pract15] SET  DISABLE_BROKER 
GO
ALTER DATABASE [pract15] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [pract15] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [pract15] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [pract15] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [pract15] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [pract15] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [pract15] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [pract15] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [pract15] SET  MULTI_USER 
GO
ALTER DATABASE [pract15] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [pract15] SET DB_CHAINING OFF 
GO
ALTER DATABASE [pract15] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [pract15] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [pract15] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [pract15] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [pract15] SET QUERY_STORE = ON
GO
ALTER DATABASE [pract15] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [pract15]
GO
/****** Object:  Table [dbo].[brands$]    Script Date: 22.12.2025 21:41:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[brands$](
	[name] [nvarchar](255) NULL,
	[id] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_brands$] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[categories$]    Script Date: 22.12.2025 21:41:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[categories$](
	[name] [nvarchar](255) NULL,
	[id] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_categories$] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[product_tags$]    Script Date: 22.12.2025 21:41:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[product_tags$](
	[product_id] [int] NULL,
	[tag_id] [int] NULL,
	[id] [int] IDENTITY(1,1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[products$]    Script Date: 22.12.2025 21:41:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[products$](
	[name] [nvarchar](255) NULL,
	[description] [nvarchar](255) NULL,
	[price] [float] NULL,
	[stock] [float] NULL,
	[rating] [float] NULL,
	[created_at] [nvarchar](255) NULL,
	[category_id] [int] NULL,
	[brand_id] [int] NULL,
	[id] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_products$] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tags$]    Script Date: 22.12.2025 21:41:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tags$](
	[name] [nvarchar](255) NULL,
	[id] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_tags$] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [pract15] SET  READ_WRITE 
GO
